name: Build Swuild

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show Swift Version
        run: swift --version

      - name: Build Swuild
        run: swift build --configuration release

      - name: Get Result Swuild binary
        id: swuild_bin_path
        run: echo "swuild_path=$(swift build --show-bin-path --configuration release)" >> $GITHUB_OUTPUT

      - name: Run Tutorial Flow
        run: "${{ steps.swuild_bin_path.outputs.swuild_path }}/Swuild run --flow-product-name Tutorial"

      - name: Run Swuild Pack Flow (packing swuild itself)
        run: "${{ steps.swuild_bin_path.outputs.swuild_path }}/Swuild run --flow-product-name SwuildPack"

      - name: Archive Swuild iteself
        uses: actions/upload-artifact@v4
        with:
          name: swuild.tar.gz
          path: .build/swuild.tar.gz
          overwrite: true
          compression-level: 0