name: Build Swuild

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show Swift Version
        run: swift --version

      - name: Build Swuild
        run: swift build --configuration release

      - name: Get Result Swuild binary
        id: swuild_bin_path
        run: echo "swuild_path=$(swift build --show-bin-path --configuration release)" >> $GITHUB_OUTPUT

      - name: Run Tutorial Flow
        run: "${{ steps.swuild_bin_path.outputs.swuild_path }}/Swuild run --flow-product-name Tutorial"